### ISSUE TITLE
GitHub Flow migration

### ISSUE THREAD

**Issue by arcticicestudio** [arcticicestudio/styleguide-git#9]
<div align="center"><img src="https://user-images.githubusercontent.com/7836623/78555431-4e318e80-780d-11ea-8ff4-52f9a9a27682.png" /></div>

# Historical Background

Back on July 22 2017, this style guide for _Git_ was created that also includes the compliance with [Git Flow][gitflow]. Generally this _branching_ model is really dynamic and can help a larger team to keep the overview of different story implementations while being able to build and deploy version _backports_. Using `develop` as the main branch also helps to make sure the `master` branch always contains stable versions.

Anyway, the model also comes with disadvantages like the overhead of keeping both `develop` and `master` in sync when tagging a new release version. The main target groups for this model are larger teams that work on projects with legacy support.

I've adapted to _Git Flow_ because I liked the idea of having one branch that reflects the actual development state, but after using it for over 6 years I don't see any advantages in it anymore compared to other great models like [GitHub Flow][githubflow]. I've checked the original _Git Flow_ blog post of _Vincent Driessen_ again and was amazed that he recently (March 5, 2020) added an update at the top of the post that exactly matches my opinion regarding the fact that _Git Flow_ is not suitable these days, comes with too much overhead and that he now recommends to use _GitHub Flow_ instead:

> ### Note of reflection (March 5, 2020)
>
> This model was conceived in 2010, now more than 10 years ago, and not very long after Git itself came into being. In those 10 years, git-flow (the branching model laid out in this article) has become hugely popular in many a software team to the point where people have started treating it like a standard of sorts — but unfortunately also as a dogma or panacea.
>
> During those 10 years, Git itself has taken the world by a storm, and the most popular type of software that is being developed with Git is shifting more towards web apps — at least in my filter bubble. Web apps are typically continuously delivered, not rolled back, and you don't have to support multiple versions of the software running in the wild.
>
> This is not the class of software that I had in mind when I wrote the blog post 10 years ago. If your team is doing continuous delivery of software, I would suggest to adopt a much simpler workflow (like [GitHub flow][githubflow]) instead of trying to shoehorn git-flow into your team.
>
> If, however, you are building software that is explicitly versioned, or if you need to support multiple versions of your software in the wild, then git-flow may still be as good of a fit to your team as it has been to people in the last 10 years. In that case, please read on.
>
> To conclude, always remember that panaceas don't exist. Consider your own context. Don't be hating. Decide for yourself.

This update perfectly reflects the way I thought about the _Git Flow_ model quite a while now.
Therefore I've finally decided to switch to _GitHub Flow_ and retire the good old `develop` in favor of `master` as the one and only *single-source-of-truth*™️.

<div align="center"><img src="https://user-images.githubusercontent.com/7836623/78555427-4bcf3480-780d-11ea-847e-d775b5f45d57.png" /></div>

# Migration Tasks

Since all _Arctic Ice Studio_ projects adhere to this guide each repository must gradually adapt to this change one after the other. Large projects like [Nord][] with [all of it's port projects][nord-ports] will require a lot more time and effort to migrate regarding the goal and tooling compatibility of the actual project.
Smaller projects like my [igloo][] _dotfile_ repository, [snowsaw][] as well as this _style guide_ repository itself are way easier and can be done within the next few weeks.

To ensure the migration is documented and the status of each repository can be tracked, this issue will be kept open and used as umbrella ticket.

Private repositories are tracked internally as well on external (private) systems while the following affected public repositories and the corresponding issue are listed below.

- [ ] arcticicestudio/arctic-landscape#
- [ ] arcticicestudio/arctic-ocean-fractal#
- [ ] arcticicestudio/icecore-hashids#
- [x] arcticicestudio/igloo#240
- [x] arcticicestudio/nord-alacritty#21
- [ ] arcticicestudio/nord-atom-syntax#
- [ ] arcticicestudio/nord-atom-ui#
- [ ] arcticicestudio/nord-brackets#
- [ ] arcticicestudio/nord-coda#
- [ ] arcticicestudio/nord-conemu#
- [ ] arcticicestudio/nord-dircolors#
- [x] arcticicestudio/nord-docs#229
- [ ] arcticicestudio/nord-eclipse-syntax#
- [x] arcticicestudio/nord-emacs#134
- [ ] arcticicestudio/nord-gedit#
- [ ] arcticicestudio/nord-gnome-terminal#
- [ ] arcticicestudio/nord-guake#
- [ ] arcticicestudio/nord-highlightjs#
- [ ] arcticicestudio/nord-hyper#
- [ ] arcticicestudio/nord-iterm2#
- [ ] arcticicestudio/nord-java#
- [x] arcticicestudio/nord-jetbrains#180
- [ ] arcticicestudio/nord-konsole#
- [ ] arcticicestudio/nord-mintty#
- [ ] arcticicestudio/nord-notepadplusplus#
- [ ] arcticicestudio/nord-putty#
- [x] arcticicestudio/nord-slack#13
- [ ] arcticicestudio/nord-sublime-text#
- [ ] arcticicestudio/nord-terminal-app#
- [ ] arcticicestudio/nord-terminator#
- [ ] arcticicestudio/nord-termite#
- [ ] arcticicestudio/nord-tilix#
- [ ] arcticicestudio/nord-tmux#
- [x] arcticicestudio/nord-vim#311
- [ ] arcticicestudio/nord-visual-studio-code#
- [ ] arcticicestudio/nord-xcode#
- [ ] arcticicestudio/nord-xfce-terminal#
- [ ] arcticicestudio/nord-xresources#
- [ ] arcticicestudio/nord#
- [ ] arcticicestudio/remark-preset-lint-arcticicestudio#
- [ ] arcticicestudio/snowsaw#
- [ ] arcticicestudio/styled-modern-normalize#
- [ ] arcticicestudio/styleguide-java#
- [x] arcticicestudio/styleguide-javascript#39
- [x] arcticicestudio/styleguide-markdown#20
- [ ] svengreb/website#

[gitflow]: https://nvie.com/posts/a-successful-git-branching-model
[githubflow]: https://guides.github.com/introduction/flow
[igloo]: https://github.com/arcticicestudio/igloo
[nord-ports]: https://www.nordtheme.com/ports
[nord]: https://www.nordtheme.com
[snowsaw]: https://github.com/arcticicestudio/snowsaw
